[ci]
steps = [
  "cargo fmt --all -- --check",
  "terraform fmt -write=false -check=true -list=true -diff=true terraform",
  "bin/dev/lint-js",
  "cargo check --quiet --all",
  "bin/ember test",
]

[github]
repo = "maxjacobson/coconut-estate"
