[package]
name = "secrets_keeper"
version = "0.0.1"
publish = false

[dependencies]
# async web framework
actix = "0.5.7"
actix-web = "0.6.8"
serde = "1.0"
serde_derive = "1.0"

# CLI interface
clap = "~2.31.2"

# logging
env_logger = "0.5.9"
log = "0.4.0"
