[package]
name = "secrets_keeper"
version = "0.0.1"
publish = false

[dependencies]
# web framework
warp = "0.1.0"

# logging
env_logger = "~0.5"
log = "~0.4"

# CLI interface
clap = "~2.31"

# Serialization/deserialization
serde = "~1.0"
serde_derive = "~1.0"
