[package]
name = "website"
version = "0.0.1"
publish = false

[dependencies]
# async web framework
actix = "~0.5"
actix-web = { version = "~0.6", features=["alpn"] }
openssl = "~0.10"

# CLI interface
clap = "~2.31"

# logging
env_logger = "~0.5"
log = "~0.4"
